models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - clothsie:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory clothsie --reload-on-changes /clothsie/wsgi.py"