# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothsie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='items_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_bought', to='clothsie_app.Item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='items_selling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_selling', to='clothsie_app.Item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='items_sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_sold', to='clothsie_app.Item'),
        ),
    ]
